version: '3.7' # Указывает версию Docker Compose

services: # Начало секции с сервисами
  sp_server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: ".env"
    ports:
      - "9178:9001"
    networks:
      - sp_network
      -
networks:
  sp_network:
    driver: bridge