name: CI/CD Pipeline for Swagger Provider API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_CATDEV }}" > private_key && chmod 600 private_key
        eval $(ssh-agent -s)
        echo "${{ secrets.SSH_PASSPHRASE }}" | SSH_ASKPASS=/bin/cat ssh-add private_key

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -p 2324 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_CATDEV }} '
          cd pincode.swagger-provider.api &&
          git pull &&
          sudo docker compose up -d --build
        '
