name: CI/CD Pipeline for Swagger Provider API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_CATDEV }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -p 2324 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_CATDEV }} '
            cd pincode.swagger-provider.api &&
            eval $(ssh-agent -s) &&
            echo "${{ secrets.SSH_PASSPHRASE }}" | SSH_ASKPASS=/bin/cat ssh-add ~/.ssh/id_rsa_github &&
            git pull &&
            sudo docker compose up -d --build &&
            sudo docker system prune -af
          '

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_CATDEV }}

      - name: Wait for container to be ready
        run: |
          ssh -o StrictHostKeyChecking=no -p 2324 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_CATDEV }} '
            until sudo docker ps | grep -q "backend-swagger"; do
              echo "Waiting for container to start...";
              sleep 5;
            done;
            echo "Container is running, starting tests..."
          '

      - name: Run tests
        run: |
          ssh -o StrictHostKeyChecking=no -p 2324 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST_CATDEV }} '
            cd pincode.swagger-provider.api &&
            yarn install &&
            yarn test:api
          '
